config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :messages do
    resources :comments
  end
  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_message
before_action :find_comment, only: [:edit, :update, :destroy]
before_action :authenticate_user!
  
  def create
	@comment = @message.comments.create(comment_params)
	@comment.user_id = current_user.id

	if @comment.save
	  redirect_to message_path(@message)
	else
	  render 'new'
	end
  end
  
  def edit
  end

  def update
	if @comment.update(comment_params)
		redirect_to message_path(@message)
	else
		render 'edit'
	end
  end

  def destroy
	@comment.destroy
	redirect_to message_path(@message)
  end

  private

  def comment_params
	params.require(:comment).permit (:content)
  end

  def find_message
	@message = Message.find(params[:message_id])
  end

  def find_comment
	@comment = @message.comments.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
	@messages = Message.all.order("created_at desc")
  end

  def show
  end

  def new
	@message = current_user.messages.build
  end

  def create
	@message = current_user.messages.build(message_params)
	if @message.save
		redirect_to root_path
	else
		render 'new'
	end
  end

  def edit
  end

  def update
	if @message.update(message_params)
	  redirect_to message_path
	else
		render 'edit'
	end
  end

  def destroy
	@message.destroy
	redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(:title, :description)
  end
  
   def find_message
	@message = Message.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>
<p>Posted by <%= comment.user.email %> <%= time_ago_in_words(@message.created_at) %> ago</p>
<% if user_signed_in? %>
<% if comment.user_id == current_user.id %>
<%= link_to 'Edit', edit_message_comment_path(comment.message, comment) %>
<%= link_to 'Delete', message_comment_path(comment.message, comment), method: :delete, data: { confirm: 'Are you sure'} %>
<% end %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label: "Comment" %>
  <%= f.button :submit, 'comment'%>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
  <%= f.input :content, label: "Comment" %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-default">
    <div class="container">
    <div class="navbar-header">
      <%= link_to "Message board", root_path, class:"navbar-brand" %>
    </div>   
    <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <% end %>
    </ul>
    <% if user_signed_in? %>
    <li><%= link_to "New Message", new_message_path, class: "navbar-right navbar-text navbar-link" %></li>
    <% end %>
    </div>
  </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: 'Message Title', error: 'Username is mandatory, please specify one' %>
  <%= f.input :description %>
  <%= f.button :submit, 'Create new message' %>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>
<%= render 'form' %>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
  <h2><%= message.title %></h2>
  <p><%= message.description %></p>
  <%= link_to "View message", message_path(message), class: 'btn btn-primary' %>
<% end %>
<br/> <br/>
<div>
<%= link_to "New message", new_message_path %>
</div>

app/views/messages/new.html.erb
<%= render 'form' %>

app/views/messages/show.html.erb
  <h2><%= @message.title %></h2>
  <p >Posted by <em><%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago</em></p>
  <p><%= @message.description %></p>
  <hr><hr>
  <%= render @message.comments %>
  <% if user_signed_in? %>
  <h3>Reply to message</h3>
  <%= render 'comments/form' %>
  <% end %>
  
  <%= link_to "Back", root_path %>
  <% if user_signed_in? %>
    <% if @message.user_id == current_user.id %>
    <%= link_to "Edit", edit_message_path(@message) %>
    <%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Hey you sure you wana delete this"} %>
  <% end %>
  <% end %>